services:
  glances:
    image: glances
    ports:
      - 61208:61208
    container_name: glances
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: "unless-stopped"
    pid: host
    build: .
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    command: "glances -w"
  glances-exporter:
    image: glances
    ports:
      - 9091:9091
    container_name: glances-exporter
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./glances.conf:/etc/glances.conf
    restart: "unless-stopped"
    pid: host
    build: .
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    command: "glances --export prometheus -C /etc/glances.conf --quiet"

