services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    dns: 
      - ${DNS_SERVER_1}
      - ${DNS_SERVER_2}
    command: serve
    volumes:
      - diun-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Etc/UTC
      - LOG_LEVEL=debug
      - DIUN_WATCH_WORKERS=20
      - DIUN_WATCH_SCHEDULE=0 */1 * * *
      - DIUN_WATCH_JITTER=30s
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
      - DIUN_NOTIF_GOTIFY_TEMPLATETITLE={{ .Entry.Image }}
      - DIUN_NOTIF_GOTIFY_TEMPLATEBODY=**${HOSTNAME}** - {{ if .Entry.Image.HubLink }}[**{{ .Entry.Image }}**]({{ .Entry.Image.HubLink }}){{ else }}**{{ .Entry.Image }}**{{ end }} has been updated.
    env_file: .env
    restart: always
volumes:
  diun-data:
