---
- name: Rollout glances container (gpu)
  hosts: all
  become: true
  ignore_unreachable: true
    
  tasks:

    - name: Copy glances folder to remote host
      ansible.builtin.copy:
        src: ./glances-gpu
        dest: /home/serveradmin/

    - name: Remove existing glances container
      ignore_errors: true
      ansible.builtin.shell:
        cmd: docker container stop glances && docker container rm glances

    - name: Run glances container
      ansible.builtin.shell:
        chdir: /home/serveradmin/glances-gpu
        cmd: docker compose pull && docker compose down && docker compose up -d

    - name: Get container status
      register: container_status
      ansible.builtin.shell:
        cmd: docker ps

    - debug:
        var: container_status.stdout_lines
