---
- name: Rollout glances container
  hosts: all
  become: true
    
  tasks:

    - name: Copy glances folder to remote host
      ansible.builtin.copy:
        src: ./glances-minimal
        dest: ~/

    - name: Run glances container
      ansible.builtin.command:
        chdir: ~/glances-minimal
        cmd: docker compose pull && docker compose down && docker compose up -d

    - name: Get container status
      register: container_status
      ansible.builtin.command:
        cmd: docker ps

    - debug:
        var: container_status.stdout_lines
