---
- name: Rollout diun container
  hosts: all
  become: true

  tasks:

    - name: Copy diun folder to remote host
      ansible.builtin.copy:
        src: ./diun
        dest: /home/serveradmin/

    - name: Build .env file
      shell: |
        cd /home/serveradmin/diun/
        rm .env
        echo DIUN_NOTIF_GOTIFY_ENDPOINT={{DIUN_NOTIF_GOTIFY_ENDPOINT}} >> .env
        echo DIUN_NOTIF_GOTIFY_TOKEN={{DIUN_NOTIF_GOTIFY_TOKEN}} >> .env
        echo DNS_SERVER_1={{DNS_SERVER_1}} >> .env
        echo DNS_SERVER_2={{DNS_SERVER_2}} >> .env
        echo HOSTNAME={{ansible_hostname}} >> .env

    - name: Run diun container
      ansible.builtin.command:
        chdir: /home/serveradmin/diun
        cmd: docker compose up -d --force-recreate

    - name: Get container status
      register: container_status
      ansible.builtin.command:
        cmd: docker ps

    - debug:
        var: container_status.stdout_lines
