---
- name: Rollout watchtower container
  hosts: all
  become: true
  ignore_unreachable: true

  tasks:

    - name: Copy watchtower folder to remote host
      ansible.builtin.copy:
        src: ./watchtower
        dest: /home/serveradmin/

    - name: Build .env file
      shell: |
        cd /home/serveradmin/watchtower/
        rm .env
        echo DNS_SERVER_1={{DNS_SERVER_1}} >> .env
        echo DNS_SERVER_2={{DNS_SERVER_2}} >> .env
        echo HOSTNAME={{ansible_hostname}} >> .env
        echo WATCHTOWER_NOTIFICATION_URL={{WATCHTOWER_NOTIFICATION_URL}} >> .env

    - name: Run watchtower container
      shell: |
        cd /home/serveradmin/watchtower/
        docker compose down
        docker compose pull
        docker compose up -d --force-recreate

    - name: Get container status
      register: container_status
      ansible.builtin.command:
        cmd: docker ps

    - debug:
        var: container_status.stdout_lines
