---
- name: Rollout portainer agent
  hosts: all
  become: true

  tasks:

    - name: Copy portainer agent folder to remote host
      ansible.builtin.copy:
        src: ./portainer_agent
        dest: /home/serveradmin/

    - name: Run portainer agent
      ansible.builtin.shell:
        chdir: /home/serveradmin/portainer_agent
        cmd: docker compose pull && docker compose down && docker compose up -d 

    - name: Get container status
      register: container_status
      ansible.builtin.command:
        cmd: docker ps

    - debug:
        var: container_status.stdout_lines
