services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    dns: 
      - ${DNS_SERVER_1}
      - ${DNS_SERVER_2}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: ${HOSTNAME}
    env_file: .env
    environment: 
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_SCHEDULE=0 0 5 * * *
    restart: always
