---
- name: Check if restart needed
  hosts: all
  become: true
  ignore_unreachable: true

  tasks:

    - name: Check if reboot-required exists
      register: reboot_required
      ansible.builtin.stat:
        path: "/var/run/reboot-required"

    - name: Send Gotify push
      ansible.builtin.uri:
        url: https://gotify.mattjsullivan.uk/message?token={{gotify_token}}
        method: POST
        body_format: json
        body:
          title: "Restart warning"
          message: "Reboot required on {{ inventory_hostname }}!"
          priority: 10
      when: reboot_required.stat is defined and reboot_required.stat.exists

    - name: Send a message to the Discord channel when reboot is required
      ignore_errors: true
      community.general.discord:
        webhook_id: "{{webhook_id}}"
        webhook_token: "{{webhook_token}}"
        content: "Reboot required on {{ inventory_hostname }}!"
      when: reboot_required.stat is defined and reboot_required.stat.exists
      delegate_to: localhost
      vars:
        ansible_become: false

    - name: post data to HTTP endpoint
      ansible.builtin.uri:
        url: https://nodered.local.mattjsullivan.uk/vm/reboot
        method: "POST"
        body_format: "json"
        body: 
          hostname: "{{inventory_hostname}}"
      when: reboot_required.stat is defined and reboot_required.stat.exists
      delegate_to: localhost
      vars:
        ansible_become: false
