---
- name: Read disk usage
  hosts: all
  become: true
  ignore_unreachable: true

  tasks:

    - name: Read disk usage
      register: disk_usage
      ansible.builtin.shell:
        cmd: "df -h / | awk 'NR==2 {print $5}'"

    - debug:
        var: disk_usage.stdout_lines[0]

    - name: Send discord message when disk space is over 80%
      ignore_errors: true
      community.general.discord:
        webhook_id: "{{webhook_id}}"
        webhook_token: "{{webhook_token}}"
        content: "Disk space on {{ inventory_hostname }} is above 80%!"
      when: disk_usage.stdout[:-1]|int > 80
      delegate_to: localhost
      vars:
        ansible_become: false
