---
- name: lm-sensors
  hosts: all
  become: true
  ignore_unreachable: true

  tasks:

    # - name: install lm-sensors package
    #   ansible.builtin.apt:
    #     pkg:  
    #       - lm-sensors

    - block:

      - name: check sensors (Intel)
        register: sensors_output
        ansible.builtin.shell:
          cmd: sensors | grep "Package"

      rescue: 

      - name: check sensors (AMD)
        register: sensors_output
        ansible.builtin.shell: 
          cmd: sensors | grep "Tctl"

    - debug:
        var: sensors_output

    - name: manipulate string (first split)
      ansible.builtin.set_fact:
        string_output: "{{ sensors_output.stdout | split('+') }}"
      when: sensors_output.changed

    - name: manipulate string (second split)
      ansible.builtin.set_fact:
        string_output: "{{ string_output[1] | split('.') }}"
      when: string_output is defined
      
    - name: manipulate string (select list element)
      ansible.builtin.set_fact:
        string_output: "{{string_output[0]}}"
      when: string_output is defined

    - name: post data to HTTP endpoint
      ansible.builtin.uri:
        url: https://nodered.local.mattjsullivan.uk/proxmox
        method: "POST"
        body_format: "json"
        body: 
          temperature: "{{string_output}}"
          hostname: "{{inventory_hostname}}"