---
- name: Copy files
  hosts: all
  become: true
  ignore_unreachable: true
  vars:
    - mode: copy

  tasks:

    - name: Copy files
      register: src_contents
      ansible.builtin.copy:
        remote_src: yes
        src: "{{src_directory}}/"
        dest: "{{dest_directory}}/"

    - name: Delete source files
      ansible.builtin.shell:
        cmd: "rm -rf {{src_directory}}/*"
      when: mode == "move"
