---
- name: run generic script 
  hosts: all
  become: true
  ignore_unreachable: true

  tasks:

    - name: run script
      register: output
      ansible.builtin.shell:
        cmd: . {{SCRIPT}}

    - debug:
        var: output
