---
- name: Update and upgrade packages through apt
  hosts: all
  become: true

  tasks:

    - name: update and upgrade
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
        autoclean: true
        autoremove: true
