---
- name: Update and upgrade packages through apt
  hosts: all
  become: true
  ignore_unreachable: true

  tasks:

    - name: update and upgrade
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
        autoclean: true
        autoremove: true

    - name: Send Gotify push
      ansible.builtin.uri:
        url: https://gotify.mattjsullivan.uk/message?token={{gotify_token}}
        method: POST
        body_format: json
        body:
          title: "Update notification"
          message: "Updates complete on {{ inventory_hostname }}!"
          priority: 10
