services:
  glances:
    image: glances
    ports:
      - 61208:61208
    container_name: glances
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: "unless-stopped"
    pid: host
    build: .
    command: "glances -w"